title: Guangwei Wang
purpose: Personal Homepage
description: Hi there, I am Guangwei Wang.
google_analytics: UA-102217502-1
theme: jekyll-theme-cayman
gem "github-pages", group: :jekyll_plugins


email: gwwang17@gmail.com
linkedin_url: https://www.linkedin.com/in/wangguangwei/
github:
  is_project_page: true
  owner_name: gwwang16
  owner_url: https://github.com/gwwang16
  repository_name: gwwang16.github.io
  repository_url: https://github.com/gwwang16