# Site settings
title: Guangwei Wang
email: gwwang17@gmail.com
url: http://guangwei.wang
description: "Hi there."
keywords: "Guangwei Wang, homepage, github pages"
skills: "PhD Student"
meta_author: Guangwei Wang
author:
  name: Wang

# descrition in about me
about:
  description1: "I am currently pursuing the Ph.D. degree in Electromechanical Engineering at the University of Macau, Macao, China. My current research interests include micro/nanorobotics, biological cell microinjection, and intelligent control, etc."
  description2: "I am passionate about Machine Learning and Robotics. I have obtained Machine Learning, Deep Learning Nanodegree from Udacity, and I am working on Robotics Nanodegree now."

# Google analytics num
google_analytics: UA-102217502-1

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus:
  shortname: gwwang

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: 2E3C47
  primary-dark-rgb: "40,60,71"
  primary: 18bc9c #80B3FF 2E3C47 #
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2E3C47 # 2c3e50 #FD6E8A Nav bar color
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Guangwei Wang
  location: Location
  social: Around the Web
  credits: Credits
  links: Links

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/wangguangwei/
  - title: github
    url: http://github.com/gwwang16
  - title: weibo
    url:
  - title: facebook
    url:

# Postal address (add as many lines as necessary)
address:
  - line: University of Macau
  - line: Macao, China

# Credits content
credits: 'Powered by Jekyll and Bootstrap. <br>Generated by <a href="https://pages.github.com">GitHub Pages</a>.'

# Friends links
links:
  - title: Jason Hu's blog
    url: http://psychonote.science/

# Build settings
markdown: kramdown
permalink: pretty
